version: "2"
services:
 shard1:
  image: mongo
  ports:
   - 20001:27018
  networks:
   - shard
  container_name: shard1
  command: mongod --shardsvr
 shard2:
  image: mongo
  ports:
   - 20002:27018
  networks:
   - shard
  container_name: shard2
  command: mongod --shardsvr
 config1:
  image: mongo
  ports:
   - 20011:27019
  networks:
   - shard
  container_name: configsvr1
  command: mongod --configsvr --replSet configrs
 config2:
  image: mongo
  ports:
   - 20012:27019
  networks:
   - shard
  container_name: configsvr2
  command: mongod --configsvr --replSet configrs
 config3:
  image: mongo
  ports:
   - 20013:27019
  networks:
   - shard
  container_name: configsvr3
  command: mongod --configsvr --replSet configrs
 mongos:
  image: mongo
  ports:
   - 20000:27017
  networks:
   - shard
  container_name: mongoshard
  command: mongos --configdb configrs/configsvr1:27019,configsvr2:27019,configsvr3:27019 --bind_ip_all
  depends_on:
   - config1
   - config2
   - config3
   - shard1
   - shard2
networks:
 shard:
  driver: bridge
