version: '2'
services:
 mongo-primary:
  image: mongo
  ports:
   - 30001:27017
  networks:
   - mongo
  container_name: mongo-primary
  command: mongod --replSet rs --keyFile=/data./keyFile
  restart: on-failure
  volumes: ./keyFile:/data/keyFile
  user: mongodb
  environment: 
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=qqq111
 mongo-secondary-1:
  image: mongo
  ports:
   - 30002:27017
  networks:
   - mongo
  container_name: mongo-secondary-1
  command: mongod --replSet rs --keyFile=/data./keyFile
  restart: on-failure
  volumes: ./keyFile:/data/keyFile
  user: mongodb
  environment: 
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=qqq111
 mongo-secondary-2:
  image: mongo
  ports:
   - 30003:27017
  networks:
   - mongo
  container_name: mongo-secondary-2
  command: mongod --replSet rs --keyFile=/data./keyFile
  restart: on-failure
  volumes: ./keyFile:/data/keyFile
  user: mongodb
  environment: 
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=qqq111
networks:
 mongo:
  driver: bridge